---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: code-server-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://nicholaswilde.github.io/helm-charts/
  timeout: 3m