---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: rancher-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://releases.rancher.com/server-charts/stable
  timeout: 3m
