apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - prometheus.yaml
secretGenerator:
- name: service-key
  namespace: observability
  options:
    disableNameSuffixHash: true
  envs:
  - cloudflare-originca-sops.env
